// This file is responsible for creating the main window of the Electron app.
import { BrowserWindow } from "electron";
import AppMenu from "./menu";
import AppTray from "./tray";

// This allows TypeScript to pick up the magic constants that's auto-generated by Forge's Webpack
// plugin that tells the Electron app where to look for the Webpack-bundled app code (depending on
// whether you're running in development or production).
declare const MAIN_WINDOW_WEBPACK_ENTRY: string;
declare const MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY: string;

class WindowManager {
  private mainWindow: BrowserWindow | null = null;

  constructor() {}

  public createWindow(): void {
    // Create the browser window.
    this.mainWindow = new BrowserWindow({
      height: 700,
      width: 600,
      resizable: false,
      webPreferences: {
        preload: MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY,
      },
    });

    // and load the index.html of the app.
    this.mainWindow.loadURL(MAIN_WINDOW_WEBPACK_ENTRY);

    // Create the menu
    const appMenu = new AppMenu(this.mainWindow);
    appMenu.buildMenu();

    // Create the tray
    const appTray = new AppTray(this.mainWindow);
    appTray.createTray();

    // Handle window close event
    this.mainWindow.on("close", (event) => {
      event.preventDefault(); // Prevents the window from actually closing

      // Minimize to tray instead
      this.mainWindow?.hide();
    });

    this.mainWindow.on("closed", () => {
      this.mainWindow = null;
    });
  }

  public getMainWindow(): BrowserWindow | null {
    return this.mainWindow;
  }
}

export default WindowManager;
