// This file is responsible for creating the main window of the Electron app.
import { BrowserWindow } from 'electron';
import AppMenu from './menu';

// This allows TypeScript to pick up the magic constants that's auto-generated by Forge's Webpack
// plugin that tells the Electron app where to look for the Webpack-bundled app code (depending on
// whether you're running in development or production).
declare const MAIN_WINDOW_WEBPACK_ENTRY: string;
declare const MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY: string;

class WindowManager {
  private mainWindow: BrowserWindow | null = null;

  constructor() {}

  public createWindow(): void {
    // Create the browser window.
    this.mainWindow = new BrowserWindow({
      height: 600,
      width: 800,
      webPreferences: {
        preload: MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY,
      },
    });

    // and load the index.html of the app.
    this.mainWindow.loadURL(MAIN_WINDOW_WEBPACK_ENTRY);

    // Create the menu
    const appMenu = new AppMenu(this.mainWindow);
    appMenu.buildMenu();

    // Open the DevTools.
    this.mainWindow.webContents.openDevTools();

    this.mainWindow.on('closed', () => {
      this.mainWindow = null;
    });
  }

  public getMainWindow(): BrowserWindow | null {
    return this.mainWindow;
  }
}

export default WindowManager;
